# Generated by Django 3.0.7 on 2020-06-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Codingfan', max_length=255),
        ),
    ]
